#  _____     ___ ____
#   ____|   |    ____|      PSX2 OpenSource Project
#  |     ___|   |____       (C)2002, David Ryan ( Oobles@hotmail.com )
#  ------------------------------------------------------------------------

#
# Change the settings, so they match your environment
#


#
# Location of PS2LIB. Requires 1.9 or later. 
#

# PS2LIB = /usr/ps2dev/ps2lib

#
# Location of PS2IP source.
#

PS2IP = $(PS2DEV)/ps2ip
