
TOPDIR = ../..

IOP_LIB = ../lib/liblwip_common.a
IOP_OBJS = etharp.o

all: $(IOP_LIB)

clean:
	-rm -f *.o

include $(TOPDIR)/Makefile.pref
include $(TOPDIR)/Makefile.global

include $(PS2LIB)/Makefile.pref
include $(PS2LIB)/Makefile.iopglobal
